### ISSUE TITLE
Unable to build bit for ice40ultra

### ISSUE THREAD

**Issue by prashantrar** [VectorBlox/risc-v#1]
Hello,

I tried running make bit for the ice40ullra breakout board as per the instructions given in the readme. I have installed the riscv32i toolchain as well as the icecube2 software from the lattice website.

make build-software is successful for me but when I run make bit this is the error that i get.

```
prashant014@Ubuntu23:~/Documents/risc-v/ice40ultra$ make build-software 
make -C software FORMAT=mem
make[1]: Entering directory '/home/prashant014/Documents/risc-v/ice40ultra/software'
mkdir -p obj/
riscv32-unknown-elf-gcc -static  -MD -Wall -std=gnu99 -O2 -fno-omit-frame-pointer -ffast-math -fno-common  -DPREALLOCATE=1 -DHOST_DEBUG=0 -c main.c -o obj/main.c.o
riscv32-unknown-elf-gcc -static  -MD -Wall -std=gnu99 -O2 -fno-omit-frame-pointer -ffast-math -fno-common  -DPREALLOCATE=1 -DHOST_DEBUG=0 -c printf.c -o obj/printf.c.o
riscv32-unknown-elf-gcc -static  -MD -Wall -std=gnu99 -O2 -fno-omit-frame-pointer -ffast-math -fno-common  -DPREALLOCATE=1 -DHOST_DEBUG=0 -c crt.S -o obj/crt.S.o
riscv32-unknown-elf-gcc -T link.ld obj/crt.S.o  obj/main.c.o obj/printf.c.o  -o test.elf -nostartfiles -ffast-math
riscv32-unknown-elf-objdump  --disassemble-all test.elf > test.dump
riscv32-unknown-elf-objcopy -O binary test.elf test.bin
head -c $((0x100)) /dev/zero | cat - test.bin | xxd -g1 -c4 | awk '{print $5$4$3$2}' > test.mem
make[1]: Leaving directory '/home/prashant014/Documents/risc-v/ice40ultra/software'
ln -sf software/*.mem test.mem
prashant014@Ubuntu23:~/Documents/risc-v/ice40ultra$ make bit
SYNPLIFY_PATH=/home/prashant014/lscc/iCEcube2.2015.08/synpbase \
SBT_DIR=/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/ \
LD_LIBRARY_PATH=/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/bin/linux/opt/synpwrap:${LD_LIBRARY_PATH} \
/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/bin/linux/opt/synpwrap/synpwrap -prj ice40ultra_syn.prj || \
 ( cat ice40ultra_Implmnt/synlog/ice40ultra_compiler.srr && exit -1)
Copyright (C) 1992-2014 Lattice Semiconductor Corporation. All rights reserved.
Child process exit with 0.
Synthesis exit by 0.
ICECUBE2=/home/prashant014/lscc/iCEcube2.2015.08 tclsh iCEcube2_flow.tcl
No arguments passed, running full backend.

Run edifparser ...
{/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/bin/linux/opt/edifparser} {/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/devices/ICE40T04.dev} {/home/prashant014/Documents/risc-v/ice40ultra/ice40ultra_Implmnt/ice40ultra.edf /home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/devices/ipfiles/iCE5LP/rgbsoft.edf } {/home/prashant014/Documents/risc-v/ice40ultra/ice40ultra_Implmnt/sbt/netlist}  -p"SWG36"  {-y} {constraints/lve_pcf_sbt.pcf} --devicename  iCE5LP4K
Lattice Semiconductor Corporation  Edif Parser
Release:        2015.08.27744
Build Date:     Oct 14 2015 16:29:25

Parsing edif file: /home/prashant014/Documents/risc-v/ice40ultra/ice40ultra_Implmnt/ice40ultra.edf...
Error: ParseEDIF /home/prashant014/Documents/risc-v/ice40ultra/ice40ultra_Implmnt/ice40ultra.edf failed
Kparser Unable to open /home/prashant014/Documents/risc-v/ice40ultra/ice40ultra_Implmnt/ice40ultra.edf
child process exited abnormally
edifparser failed:CHILDSTATUS 24163 1
ICECUBE2=/home/prashant014/lscc/iCEcube2.2015.08 tclsh iCEcube2_flow.tcl test.mem imem.list
Initializing memory from memory file test.mem and list file imem.list.
Initializing memory files: init_00.imem init_01.imem init_02.imem init_03.imem init_04.imem init_05.imem init_06.imem init_07.imem init_08.imem init_09.imem init_10.imem init_11.imem init_12.imem init_13.imem init_14.imem init_15.imem
LD_LIBRARY_PATH=/home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/lib/linux/opt:${LD_LIBRARY_PATH} /home/prashant014/lscc/iCEcube2.2015.08/sbt_backend/bin/linux/opt/meminitializer --des-lib ice40ultra_Implmnt/sbt/netlist/oadb-top --mem-list-file imem.list
Lattice Semiconductor Corporation  Memory Initializer
Release:        2015.08.27744
Build Date:     Oct 14 2015 17:16:04

oaInterface::OpenLib_Design OpenLibrary failed ice40ultra_Implmnt/sbt/netlist/oadb-top BFPGA_DESIGN_rt
miMemInitializer::Open OpenLib_Design failed 
Unable to open design
MemContent Initialization failed

Makefile:30: recipe for target 'ice40ultra_Implmnt/sbt/outputs/bitmap/top_bitmap.hex' failed
make: *** [ice40ultra_Implmnt/sbt/outputs/bitmap/top_bitmap.hex] Error 255
prashant014@Ubuntu23:~/Documents/risc-v/ice40ultra$ 
```

**Comment by vanjoe** [comment]
Hi thanks for trying out our.

Can you try building the bitstream through the gui tools? run `/home/prashant014/lscc/iCEcube2.2015.08/iCEcube2` then open `ice40ultra_sbt.project`

**Comment by vanjoe** [comment]
Also, if that doesn't help you fix it can you give me the log file?
ice40ultra_Implmnt/synlog/ice40ultra_compiler.srr

**Comment by prashantrar** [comment]
hi,
as you said im able to generate the bitstream for the ice40ultra. I just tried the older version of lattice icecube2, maybe you could add it in the readme, it works fine when we use the "iCEcube2 2015-04 for Linux"  GUI to build bitstream, but the command "make bit" still fails with the same error even with the older version of icecube2.

Also if you could add some instructions as to how to simulate and run the code compiled with riscv32-unknown-elf-gcc it would be great. Does this also use a similar front-end server type of link to run binaries compiled with riscv gcc on the core

**Comment by vanjoe** [comment]
Hi,

If i understand prpoerly, you were able to build with make using 2015.08?
This is troubling to me since I am able to build with both 2015.08 and
2015.04 from the command line.I don't believe you can initialize the memory
from the GUI, you need to use the command line. Try the following workflow

* build bitstream from GUI
* run `make -t syn` (this may not be necessary)
* run `make bit` (this completes the build, initialising the blockrams with
content generated during `make build-software`)

To simulate I use modelsim. There is a version that comes free with
altera's tools that I use.

If you have more questions and would like to talk on the phone in real
time, send me an email directly to joel@vectorblox <joel@vectorbloz.com>.com

**Comment by prashantrar** [comment]
Yes im able to build with the flow you said

Basically if i give the make commands in order of

    >make build-software
    >sudo make syn
    >sudo make bit


then it works just fine with both versions of the latice icecube2 software, i guess sudo permissions was the issue. 

It is working fine now maybe you could just put in a word in the readme. 

This issue can be closed

**Comment by vanjoe** [comment]
That seems odd. 
If you feel like it could you take a look at look at which file it is having permissions trouble with? You shouldn't need root permissions to run those commands.

**Comment by prashantrar** [comment]
I will do that...

**Comment by prashantrar** [comment]
Just to confirm, are there any special flags/options with which we need to build the 32bit riscv toolchain for 
    >make build-software

I have used the following to install the 32bit riscv gnu toolchain

    >../configure --with-xlen=32 --with-arch=I --prefix=/opt/riscv32i

Is it correct??

**Comment by prashantrar** [comment]
This issue can be closed, i was trying the build in a shared pc and hence it wasnt  building without sudo, when i tried on my personal pc it worked fine
